# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков (выполняется)
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика (выполняется)
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP33",
  "description": "Датчик на кухне за холодильником"
}

###

# обновление датчика (выполняется)
PATCH {{baseUrl}}/sensors/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения (выполняется)
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 2,
  "temperature": 22.8
}

###

# получение информации по датчику (выполняется)
GET {{baseUrl}}/sensors/1/
Content-Type: application/json
