# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение датчиков (выполняется)
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# создание датчика (выполняется)
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP3666",
  "description": "Датчик Мешкова"
}

###

# обновление датчика (выполняется)
PATCH {{baseUrl}}/sensors/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения (выполняется)
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 3,
  "temperature": 39.9
}

###

# получение информации по датчику (выполняется)
GET {{baseUrl}}/sensors/3/
Content-Type: application/json
